language: python

python:
  - "3.4"
  - "3.5"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # install Java 8 as required by vnu.jar
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

install: 
  - "pip install -r requirements_dev.txt"
  - wget "https://github.com/validator/validator/releases/download/16.3.3/vnu.jar_16.3.3.zip"; unzip vnu.jar_16.3.3.zip

script:
  - "flake8 ."
  - "DJANGO_SETTINGS_MODULE=cove.settings py.test cove --cov"
  - "DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360 --cov-append --cov"
  - "DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds --cov-append --cov"
  - "python manage.py migrate; python manage.py compilemessages; DEBUG=false ALLOWED_HOSTS=localhost python manage.py runserver & java -jar dist/vnu.jar http://localhost:8000/ http://localhost:8000/360/ http://localhost:8000/ocds/ 'http://localhost:8000/360/?source_url=https://github.com/OpenDataServices/cove/raw/master/cove/fixtures/WellcomeTrust-grants_2_grants.csv' 'http://localhost:8000/ocds/?source_url=https://github.com/OpenDataServices/cove/raw/master/cove/fixtures/tenders_releases_2_releases.json' 'http://localhost:8000/360/common_errors/'"

after_success: coveralls
