language: python

python:
  - "3.4"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - "pip install -r requirements_dev.txt --use-mirrors"

script:
    - "flake8 ."
    - "py.test --cov cove"

after_success: coveralls
