name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Python 3.8 is used by the IATI live cove servers
        python-version: [ '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install requirements_dev.txt
      run: pip install -r requirements_dev.txt
    - name: Install requirements_iati.txt
      run: pip install -r requirements_iati.txt
    - name: Install Ubuntu Translation Libraries
      run: sudo apt install gettext
    - name: Test IATI
      run: py.test -n 2 cove_iati --cov-append --cov
    - name: Migrate Database
      run: python manage.py migrate
    - name: Compile Messages
      run: python manage.py compilemessages
    - name: Report to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
